## 该程序由 lmq8267 编写
name: 编译vnt_for_android

on:
   workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: 设置 JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: 构建 APK
        run: |
         git clone https://github.com/lbl8603/VntApp /opt/vnt-android
         cd /opt/vnt-android
         #bash ./gradlew assembleDebug --stacktrace
         sed -i 's|7.2|6.9|g' ./gradle/wrapper/gradle-wrapper.properties
         #echo "org.gradle.warning.mode=all" >>/opt/vnt-android/gradle.properties
         bash ./gradlew assembleRelease
      - name: vnt
        run: |
         find /opt/vnt-android/ -name  "apk"
         cd /opt/vnt-android/app/build/outputs/apk/release
         du -k app-release-unsigned.apk
      - name : 上传
        uses: actions/upload-artifact@master
        if: always()
        with:
         name: vnt_for_android
         path: /opt/vnt-android/app/build/outputs/apk/release/app-release-unsigned.apk
