## 此编译方法是由 lmq8267 搬到网上来实现的
name: 编译hin2n_for_android

on:
   workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: 下载工具链
        run: |
          #下载jdk sdk ndk工具链
          wget -c -q https://github.com/lucktu/compile/releases/download/toolchain/hin2n_byhj.tar.gz -P /opt/gcc/
          tar -xf /opt/gcc/hin2n_byhj.tar.gz -C /opt/gcc/
          #赋予权限以防需要权限
          #sudo chmod 777 -R /opt/gcc/
          #下载hin2n源码
          git clone https://github.com/switch-iot/hin2n.git --depth=1 --recurse-submodules /opt/hin2n-android
      - name: 构建 APK
        run: |
         cd /opt/hin2n-android/Hin2n_android
         #设置编译环境
         #sudo apt-get install git automake libssl-dev make gcc
         export JAVA_HOME=/opt/gcc/java/jdk1.8.0_202
         export JRE_HOME=/opt/gcc/java/jdk1.8.0_202/jre
         export CLASSPATH=.:$JAVA_HOME/lib:$JRE_HOME/lib:$CLASSPATH
         export PATH=$JAVA_HOME/bin:$JRE_HOME/bin:$PATH
         export ANDROID_HOME=/opt/gcc/Android/sdk
         export ANDROID_NDK_HOME=$ANDROID_HOME/ndk-bundle
            
         #添加没有生效的定义
         sed -i '/eee->last_sup = 0;/i int supernode_connect (n2n_edge_t *eee);' ./app/src/main/cpp/edge_jni/edge_android_v2.c
         sed -i '/now = time(NULL);/i void send_query_peer (n2n_edge_t *eee, const n2n_mac_t dst_mac);' ./app/src/main/cpp/edge_jni/edge_android_v2.c
         sed -i '/if(eee->conf.tuntap_ip_mode == TUNTAP_IP_MODE_SN_ASSIGN) {/i void send_register_super (n2n_edge_t *eee);' ./app/src/main/cpp/edge_jni/edge_android_v2.c
         sed -i '/if(FD_ISSET(eee->sock, &socket_mask)) {/i int fetch_and_eventually_process_data (n2n_edge_t *eee, SOCKET sock, uint8_t *pktbuf, uint16_t *expected, uint16_t *position, time_t now);' ./app/src/main/cpp/edge_jni/edge_android_v2.c
         
         #bash ./gradlew assembleRelease
         ./gradlew assemble
      - name: 打包hin2n
        run: |
         cd /opt/hin2n-android/Hin2n_android/app/build/outputs/apk
         ls -R .
         #du -k app-release-unsigned.apk
         mkdir -p /opt/hin2n
         cd /opt
         mv /opt/hin2n-android/Hin2n_android/app/build/outputs/apk/normalAllarch/debug/hin2n_v1.0-rc1_4_allarch_normal.apk /opt/hin2n/hin2n_v1.0-rc1_4_allarch_normal.apk
         mv /opt/hin2n-android/Hin2n_android/app/build/outputs/apk/normalArm/debug/hin2n_v1.0-rc1_4_arm_normal.apk /opt/hin2n/hin2n_v1.0-rc1_4_arm_normal.apk
         mv /opt/hin2n-android/Hin2n_android/app/build/outputs/apk/normalX86/debug/hin2n_v1.0-rc1_4_x86_normal.apk /opt/hin2n/hin2n_v1.0-rc1_4_x86_normal.apk
         #zip -r hin2n-android.zip /opt/hin2n
      - name : 上传
        uses: actions/upload-artifact@master
        if: always()
        with:
         name: hin2n_for_android
         path: /opt/hin2n/*
