name: 编译群晖ds213j_vnt-cli

on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:
env:
  TZ: Asia/Shanghai
  CARGO_TERM_COLOR: always
jobs:
  check:
    runs-on: ubuntu-latest
    outputs:
      ver: ${{ steps.getversion.outputs.ver }}
      cver: ${{ steps.getversion.outputs.cver }}
    steps:
      -
        name: 检查更新
        id: getversion
        run: |
          ver=`curl https://api.github.com/repos/lbl8603/vnt/releases/latest | jq -r '.tag_name'`
          cver=`curl https://api.github.com/repos/lucktu/compile/releases/latest | jq -r '.tag_name'`
          echo "ver=${ver}" >> $GITHUB_OUTPUT
          echo "cver=${cver}" >> $GITHUB_OUTPUT

  build:
    runs-on: ubuntu-latest
    needs: check
    if: ${{ needs.check.outputs.ver != needs.check.outputs.cver }}
    steps:
      -
        name: 检查代码仓库
        uses: actions/checkout@v3
      - 
        name: 编译
        run: |
          mkdir -p /opt/musl_gcc 
          wget -c https://github.com/lucktu/compile/releases/download/ds213j/armada370-gcc493_glibc220_hard-GPL.txz -P /opt/musl_gcc/
          tar -Jxvf /opt/musl_gcc/armada370-gcc493_glibc220_hard-GPL.txz -C /opt/musl_gcc/
          rustup target add armv7-unknown-linux-gnueabihf
          export PATH=$PATH:/opt/musl_gcc/arm-unknown-linux-gnueabi/bin
          export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/opt/musl_gcc/arm-unknown-linux-gnueabi/lib
          rustup target add armv7-unknown-linux-gnueabihf
          cat >>~/.cargo/config <<EOF
          [target.armv7-unknown-linux-gnueabihf]
          linker = "arm-unknown-linux-gnueabi-gcc"
          #rustflags = ["-C", "target-feature=+crt-static","-C", "strip=symbols"]  #编译静态选项 默认编译动态版
          EOF
          git clone https://github.com/lbl8603/vnt -b ${{ needs.check.outputs.ver }} /opt/vnt
          cd /opt/vnt
          #默认编译全功能版 --features openssl-vendored
          cargo build --package vnt-cli --target=armv7-unknown-linux-gnueabihf --release --features openssl-vendored
          echo "build_time=$(date '+%Y-%m-%d %H:%M:%S')" >> $GITHUB_ENV
      - 
        name: 发布
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.compile_231005 }}
          body: |
           > ### 编译时间 ：${{ env.build_time }}
           
           **适用于群晖ds213j**
           
           **[官方更新说明](https://github.com/lbl8603/vnt/releases)**
          tag_name: vnt-cli_${{ needs.check.outputs.ver }}
          files: |
              /opt/vnt/target/armv7-unknown-linux-gnueabihf/release/vnt-cli
      - 
       name: 删除工作流
       uses: GitRML/delete-workflow-runs@main
       with:
        token: ${{ secrets.compile_231005 }}
        retain_days: 2
        keep_minimum_runs: 0
